import { test, expect } from '../../fixtures/app.fixture';
import { AddEmployeePage } from '../../pages/add-employee.page';
import { EmployeeListPage, EmployeeColumn } from '../../pages/employee-list.page';
import { EmployeeRecordPage } from '../../pages/employee-record.page';
import { WRITES_ENABLED, uniqueSuffix } from '../../utils/test-data';

/**
 * Workflow: hire an employee (create -> verify -> remove).
 *
 * Business process — a new starter is added to PIM, appears in the employee
 * register, and their record opens with the sections HR then completes.
 *
 * OPT-IN. This mutates data, so it is skipped unless `E2E_ALLOW_WRITES=1`. The
 * default target is a shared public demo and creating records on every run
 * pollutes a resource other people depend on. Prefer running it against your own
 * instance via `BASE_URL`.
 *
 * NOT VERIFIED END-TO-END. Every selector below was read off the live
 * application, but the create and delete steps were never executed against it —
 * writing to the shared demo was intentionally not done. Treat this spec as
 * reviewed-but-unrun until it passes against an instance you own.
 *
 * Cleanup: `afterEach` removes whatever the test created, so a failure part-way
 * through does not leave an orphan record behind.
 */
test.describe('Workflow: hire an employee', () => {
  test.skip(!WRITES_ENABLED, 'Write workflows are opt-in — set E2E_ALLOW_WRITES=1 to run them');

  const created: string[] = [];

  test.afterEach(async ({ page }) => {
    // Remove every employee this test created, identified by its unique last name.
    for (const lastName of created.splice(0)) {
      const list = new EmployeeListPage(page);
      await list.goto();
      await list.fillEmployeeId('');
      await list.selectEmployeeName(lastName).catch(() => undefined);
      await list.search();

      if ((await list.rows.count()) > 0) {
        await list.deleteRow(0);
      }
    }
  });

  test('adds a new starter, finds them in the register and opens their record @workflow', async ({
    page,
  }) => {
    const suffix = uniqueSuffix();
    const firstName = 'E2eStarter';
    const lastName = `Auto${suffix}`;

    // Step 1 — HR opens the new-starter form.
    const addEmployee = new AddEmployeePage(page);
    await addEmployee.goto();

    // Step 2 — they record the new starter's name. The employee id is
    // pre-generated by OrangeHRM; it is captured to assert on later.
    const employeeId = await addEmployee.employeeId();
    await addEmployee.fillnames(firstName, lastName);

    // Step 3 — saving creates the employee and opens their record.
    const empNumber = await addEmployee.saveAndOpenRecord();
    created.push(lastName);

    const record = new EmployeeRecordPage(page);
    await record.waitForReady();
    await record.expectTabsVisible();
    expect(record.employeeNumber()).toBe(empNumber);

    // Step 4 — the new starter now appears in the employee register.
    const list = new EmployeeListPage(page);
    await list.goto();
    await list.fillEmployeeId(employeeId);
    await list.search();

    await expect(list.rows.first()).toBeVisible();
    await expect(list.cell(0, EmployeeColumn.FirstName)).toHaveText(firstName);
    await expect(list.cell(0, EmployeeColumn.LastName)).toHaveText(lastName);
  });

  test('rejects a new starter with no name @workflow', async ({ page }) => {
    const addEmployee = new AddEmployeePage(page);
    await addEmployee.goto();

    await addEmployee.save();

    // First and last name are both mandatory; the middle name is not.
    await expect(addEmployee.fieldErrors.first()).toBeVisible();
    await expect(addEmployee.fieldErrors.first()).toHaveText('Required');
    await expect(page).toHaveURL(/\/pim\/addEmployee$/);
  });
});
